# Generated by Django 5.2.3 on 2025-06-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserClass',
        ),
    ]
