# Generated by Django 5.2.3 on 2025-06-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_user_userclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
